### ISSUE TITLE
Log area is smaller than necessary

### ISSUE THREAD

**Issue by mbertheau** [or/jeeves#3]
On the build detail page the log area is maybe 300 pixels high, which is very inconvenient if your monitor has 1200 pixels vertically available (for each of the over 2000 rows of pixels!)

**Comment by or** [comment]
It's now up to 1000px high. The log area definitely needs a lot more styling, but for now it's also black and the redundant padding of the parent panel is gone.

**Comment by mbertheau** [comment]
For the record, this happened in fa37fec90.
